version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  database:
    image: postgres:16.3
    container_name: jl-postgres-db
    environment:
      POSTGRES_USER: ${DEV_USERNAME}
      POSTGRES_PASSWORD: ${DEV_PASSWORD}
      POSTGRES_DB: ${SPRING_OBRA_DB}
    ports:
      - "5433:5432"
    volumes:
      - jl-prumo-dev:/var/lib/postgresql/data

  # Serviço do Keycloak
  #keycloak:
  #  image: quay.io/keycloak/keycloak:25.0.6
  #  container_name: jl-keycloak
  #  environment:
  #    KEYCLOAK_ADMIN: ${DEV_USERNAME}
  #    KEYCLOAK_ADMIN_PASSWORD: ${DEV_PASSWORD}
  #    KC_DB: postgres
  #    KC_DB_URL: jdbc:postgresql://database:5432/${KEYCLOAK_DB}
  #    KC_DB_USERNAME: ${DEV_USERNAME}
  #    KC_DB_PASSWORD: ${DEV_PASSWORD}
  #    KC_HOSTNAME: localhost
  #  command: start-dev
  #  ports:
  #    - "8081:8080"
  #  depends_on:
  #    - database

  # Serviço do backend Spring Boot
  #backend:
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  container_name: jl-spring-backend
  #  environment:
  #    SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME}
  #    SPRING_DATASOURCE_USERNAME: ${DB_USER}
  #    SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  #    KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
  #    KEYCLOAK_REALM: sua_realm
  #    KEYCLOAK_RESOURCE: seu_cliente_id
  #    KEYCLOAK_SSL_REQUIRED: none
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - keycloak

  # Serviço do frontend Node.js
  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  container_name: jl-node-frontend
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - backend

# Define um volume para persistir os dados do PostgreSQL
volumes:
  jl-prumo-dev:

#Executar Docker Compose
# docker-compose up --build